name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Log in to Docker Hub
        uses: docker/login-action@3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@5.5.1
        with:
          images: cadms/bacmet

      - name: Build and push Docker image
        uses: docker/build-push-action@5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
